# Generated by Django 6.1.1 on 2026-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month']},
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='allowance',
            new_name='allowances',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='deduction',
            new_name='deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='gross_salary',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
